repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
-   repo: local
    hooks:
    -   id: pytest
        name: run tests
        entry: pytest tests -vv
        language: system
        always_run: true
        pass_filenames: false