# Setup
title: IAI MovieBot
description: IAI MovieBot is a conversational recommender system for movies.

baseurl: ""
paginate: 1

# About/contact
author:
  name: IAI group
  url: http://iai.group

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
