# Setup
title: IAI MovieBot
tagline:

baseurl: ""
paginate: 1

# About/contact
author:
  name: IAI group
  url: http://iai.group

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
