# Participants' configuration
usersim_config: data/config/usersim_agenda_config.yaml
agent_config: data/config/moviebot_config_rb_nlu.yaml

# Model's parameters
model:
  algorithm: a2c
  policy_input_size: 8
  hidden_size: 128
  model_path: models/policy/a2c_policy.pt

# Training hyperparameters
hyperparams:
  n_envs: 10
  n_episodes: 1000
  n_steps_per_episode: 128
  gamma: 0.999
  lambda: 0.95
  ent_coef: 0.01

use_intents: False
turn_penalty: 0.0
no_nlu: False

debug: False
